#!/usr/bin/env bash
set -e

if [ -f ".venv/bin/activate" ]; then
    source .venv/bin/activate
fi

python scripts/gen_ids.py --check
ruff check python/ tests/ integtests/
ruff format --check python/ tests/ integtests/
