from ._sts_sim import (
    EndTurnAction,
    PlayCardAction,
    SelectTargetAction,
    CombatState,
    Monster,
    RunState,
    apply as _apply_rust,
    draw_overgrowth_elite,
    draw_overgrowth_monster_sequence,
    evaluate,
    fight_outcomes_per_fight,
    hp_lost_per_fight,
    is_terminal,
    legal_actions,
    mcts_action_values,
    mcts_search,
    optimal_value,
    random_rollout,
    redeterminized,
    reward,
    run_apply,
    run_is_terminal,
    run_legal_actions,
    simulate_hp_lost,
    simulate_run_outcome,
    simulate_run_outcomes,
)


def apply(state, action):
    """Apply an action to a CombatState. Accepts both Action objects and strings."""
    return _apply_rust(state, str(action))


__all__ = [
    "EndTurnAction",
    "PlayCardAction",
    "SelectTargetAction",
    "CombatState",
    "Monster",
    "RunState",
    "apply",
    "draw_overgrowth_elite",
    "draw_overgrowth_monster_sequence",
    "evaluate",
    "fight_outcomes_per_fight",
    "hp_lost_per_fight",
    "is_terminal",
    "legal_actions",
    "mcts_action_values",
    "mcts_search",
    "optimal_value",
    "random_rollout",
    "redeterminized",
    "reward",
    "run_apply",
    "run_is_terminal",
    "run_legal_actions",
    "simulate_hp_lost",
    "simulate_run_outcome",
    "simulate_run_outcomes",
]
