#!/usr/bin/env python3
"""Generate src/ids.rs from cards.rs, monsters.rs, and NameMap.cs."""

import re
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent  # repo root — scripts/ is one level down


def display_to_variant(display: str) -> str:
    """'Iron Wave' → 'IronWave', 'Evil Eye' → 'EvilEye'"""
    parts = re.sub(r"[^a-zA-Z0-9 ]", " ", display).split()
    return "".join(p[0].upper() + p[1:] for p in parts)


def to_screaming_snake(s: str) -> str:
    """CamelCase or display name → SCREAMING_SNAKE_CASE."""
    s = s.replace(" ", "_")
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s)
    return s.upper()


def cards_from_rust() -> list[str]:
    src = (REPO / "src/cards.rs").read_text()
    return re.findall(r'^\s+"([^"]+)"\s*=>\s*Some\(CardData', src, re.MULTILINE)


def monsters_from_rust() -> list[str]:
    src = (REPO / "src/monsters.rs").read_text()
    # opening_intent function has one match arm per monster
    m = re.search(r"fn opening_intent\([^)]+\)[^{]*\{(.*?)\n    \}", src, re.DOTALL)
    if not m:
        print("ERROR: could not find opening_intent", file=sys.stderr)
        sys.exit(1)
    return re.findall(r'"([^"]+)"\s*=>', m.group(1))


def sts2_maps_from_namemap() -> tuple[dict, dict]:
    """Returns (card_map, monster_map) where each is {sim_name: sts2_id}."""
    src = (REPO / "bridge_mod/Code/NameMap.cs").read_text()

    def extract_section(name: str) -> dict:
        m = re.search(rf"{name}\s*=\s*new\(\)\s*\{{(.*?)\}};", src, re.DOTALL)
        if not m:
            return {}
        result = {}
        for entry in re.finditer(r'\["([A-Z_]+)"\]\s*=\s*"([^"]+)"', m.group(1)):
            sts2_id, sim_name = entry.group(1), entry.group(2)
            result[sim_name] = sts2_id
        return result

    return extract_section("CardNameMap"), extract_section("MonsterNameMap")


def generate() -> str:
    cards = cards_from_rust()
    monsters = monsters_from_rust()
    card_sts2, monster_sts2 = sts2_maps_from_namemap()

    # ── Card variant info ─────────────────────────────────────────────────────
    # Special case: Strike/Defend are shared cards; use Ironclad suffix for now.
    CHAR_RENAMES = {
        "Strike": "StrikeIronclad",
        "Defend": "DefendIronclad",
    }
    CARD_STS2_OVERRIDES = {
        "Strike": "STRIKE_IRONCLAD",
        "Defend": "DEFEND_IRONCLAD",
    }

    card_rows: list[tuple[str, str, str]] = []  # (variant, display, sts2_id)
    seen_variants: set[str] = set()
    for display in cards:
        variant = CHAR_RENAMES.get(display, display_to_variant(display))
        sts2_id = CARD_STS2_OVERRIDES.get(display) or card_sts2.get(display)
        if sts2_id is None:
            # Derive from display name
            sts2_id = to_screaming_snake(display_to_variant(display))
        if variant in seen_variants:
            print(f"WARNING: duplicate card variant {variant!r}", file=sys.stderr)
        seen_variants.add(variant)
        card_rows.append((variant, display, sts2_id))

    # ── Monster variant info ──────────────────────────────────────────────────
    monster_rows: list[tuple[str, str, str]] = []
    seen_m: set[str] = set()
    for display in monsters:
        variant = display_to_variant(display)
        sts2_id = monster_sts2.get(display) or to_screaming_snake(variant)
        if variant in seen_m:
            continue  # skip duplicates
        seen_m.add(variant)
        monster_rows.append((variant, display, sts2_id))

    # ── Generate Rust ─────────────────────────────────────────────────────────
    lines: list[str] = []
    W = lines.append

    W("//! Typed identifiers for cards and monsters.")
    W("//! This file is generated by scripts/gen_ids.py — do not edit directly.")
    W("//! Re-run `cargo run --bin gen_ids` (or `python scripts/gen_ids.py`) to regenerate.")
    W("")
    W("// ── CardId ───────────────────────────────────────────────────────────────────")
    W("")
    W("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    W("pub enum CardId {")
    for variant, display, _ in card_rows:
        W(f'    {variant}, // "{display}"')
    W("}")
    W("")
    W("impl CardId {")

    # as_str
    W("    /// Canonical sim display name.")
    W("    pub fn as_str(self) -> &'static str {")
    W("        match self {")
    for variant, display, _ in card_rows:
        W(f'            CardId::{variant} => "{display}",')
    W("        }")
    W("    }")
    W("")

    # from_str
    W("    /// Parse from sim display name. Returns `None` for unknown names.")
    W("    pub fn from_str(s: &str) -> Option<Self> {")
    W("        match s {")
    # Need to handle cases where multiple variants share a display name (Strike/Defend currently only Ironclad)
    seen_displays: set[str] = set()
    for variant, display, _ in card_rows:
        if display not in seen_displays:
            W(f'            "{display}" => Some(CardId::{variant}),')
            seen_displays.add(display)
    W("            _ => None,")
    W("        }")
    W("    }")
    W("")

    # sts2_id
    W("    /// STS2 model ID (e.g. `STRIKE_IRONCLAD`).")
    W("    pub fn sts2_id(self) -> &'static str {")
    W("        match self {")
    for variant, _, sts2_id in card_rows:
        W(f'            CardId::{variant} => "{sts2_id}",')
    W("        }")
    W("    }")
    W("")

    # from_sts2
    W("    /// Parse from STS2 model ID. Returns `None` for unknown IDs.")
    W("    pub fn from_sts2(s: &str) -> Option<Self> {")
    W("        match s {")
    seen_sts2: set[str] = set()
    for variant, _, sts2_id in card_rows:
        if sts2_id not in seen_sts2:
            W(f'            "{sts2_id}" => Some(CardId::{variant}),')
            seen_sts2.add(sts2_id)
    W("            _ => None,")
    W("        }")
    W("    }")
    W("")

    # all
    W("    /// Every `CardId` variant.")
    W("    pub fn all() -> &'static [CardId] {")
    W("        &[")
    for variant, _, _ in card_rows:
        W(f"            CardId::{variant},")
    W("        ]")
    W("    }")
    W("}")
    W("")
    W("// ── MonsterId ────────────────────────────────────────────────────────────────")
    W("")
    W("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    W("pub enum MonsterId {")
    for variant, display, _ in monster_rows:
        W(f'    {variant}, // "{display}"')
    W("}")
    W("")
    W("impl MonsterId {")

    W("    /// Canonical sim display name.")
    W("    pub fn as_str(self) -> &'static str {")
    W("        match self {")
    for variant, display, _ in monster_rows:
        W(f'            MonsterId::{variant} => "{display}",')
    W("        }")
    W("    }")
    W("")

    W("    /// Parse from sim display name.")
    W("    pub fn from_str(s: &str) -> Option<Self> {")
    W("        match s {")
    for variant, display, _ in monster_rows:
        W(f'            "{display}" => Some(MonsterId::{variant}),')
    W("            _ => None,")
    W("        }")
    W("    }")
    W("")

    W("    /// STS2 model ID (e.g. `JAW_WORM`).")
    W("    pub fn sts2_id(self) -> &'static str {")
    W("        match self {")
    for variant, _, sts2_id in monster_rows:
        W(f'            MonsterId::{variant} => "{sts2_id}",')
    W("        }")
    W("    }")
    W("")

    W("    /// Parse from STS2 model ID.")
    W("    pub fn from_sts2(s: &str) -> Option<Self> {")
    W("        match s {")
    seen_sts2_m: set[str] = set()
    for variant, _, sts2_id in monster_rows:
        if sts2_id not in seen_sts2_m:
            W(f'            "{sts2_id}" => Some(MonsterId::{variant}),')
            seen_sts2_m.add(sts2_id)
    W("            _ => None,")
    W("        }")
    W("    }")
    W("")

    W("    /// Every `MonsterId` variant.")
    W("    pub fn all() -> &'static [MonsterId] {")
    W("        &[")
    for variant, _, _ in monster_rows:
        W(f"            MonsterId::{variant},")
    W("        ]")
    W("    }")
    W("}")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    code = generate()
    out = REPO / "src" / "ids.rs"
    out.write_text(code)
    print(f"Written {out} ({code.count(chr(10))} lines)")
