//! Typed identifiers for cards and monsters.
//!
//! The `define_ids!` macro below expands each table row into `as_str`,
//! `from_str`, `sts2_id`, `from_sts2`, and `all` — all O(1) match arms.
//!
//! **Do not edit the generated regions by hand.** Edit `data/cards.toml` or
//! `data/monsters.toml` and run `python scripts/gen_ids.py`.
//! After adding a variant, also add its card/monster logic in cards.rs / monsters.rs.

macro_rules! define_ids {
    ($name:ident { $($variant:ident => $display:literal / $sts2:literal),* $(,)? }) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum $name { $($variant),* }

        impl $name {
            /// Canonical sim display name.
            pub fn as_str(self) -> &'static str {
                match self { $($name::$variant => $display),* }
            }
            /// Parse from sim display name. Returns `None` for unknown names.
            pub fn from_str(s: &str) -> Option<Self> {
                match s { $($display => Some($name::$variant),)* _ => None }
            }
            /// STS2 model ID (screaming snake case).
            pub fn sts2_id(self) -> &'static str {
                match self { $($name::$variant => $sts2),* }
            }
            /// Parse from STS2 model ID. Returns `None` for unknown IDs.
            pub fn from_sts2(s: &str) -> Option<Self> {
                match s { $($sts2 => Some($name::$variant),)* _ => None }
            }
            /// Every variant, in declaration order.
            pub fn all() -> &'static [Self] {
                &[$($name::$variant),*]
            }
        }
    };
}

// ── CardId / MonsterId ───────────────────────────────────────────────────────

// BEGIN GENERATED by scripts/gen_ids.py — do not edit
define_ids!(CardId {
    StrikeIronclad  => "Strike"          / "STRIKE_IRONCLAD",
    DefendIronclad  => "Defend"          / "DEFEND_IRONCLAD",
    Bash            => "Bash"            / "BASH",
    IronWave        => "Iron Wave"       / "IRON_WAVE",
    Inflame         => "Inflame"         / "INFLAME",
    SwordBoomerang  => "Sword Boomerang" / "SWORD_BOOMERANG",
    Thunderclap     => "Thunderclap"     / "THUNDERCLAP",
    Rage            => "Rage"            / "RAGE",
    DemonForm       => "DemonForm"       / "DEMON_FORM",
    CrimsonMantle   => "CrimsonMantle"   / "CRIMSON_MANTLE",
    Inferno         => "Inferno"         / "INFERNO",
    Aggression      => "Aggression"      / "AGGRESSION",
    DarkEmbrace     => "DarkEmbrace"     / "DARK_EMBRACE",
    FeelNoPain      => "FeelNoPain"      / "FEEL_NO_PAIN",
    Barricade       => "Barricade"       / "BARRICADE",
    Juggernaut      => "Juggernaut"      / "JUGGERNAUT",
    FlameBarrier    => "FlameBarrier"    / "FLAME_BARRIER",
    Colossus        => "Colossus"        / "COLOSSUS",
    Corruption      => "Corruption"      / "CORRUPTION",
    Cruelty         => "Cruelty"         / "CRUELTY",
    Mangle          => "Mangle"          / "MANGLE",
    OneTwoPunch     => "OneTwoPunch"     / "ONE_TWO_PUNCH",
    PommelStrike    => "Pommel Strike"   / "POMMEL_STRIKE",
    Bloodletting    => "Bloodletting"    / "BLOODLETTING",
    BloodWall       => "BloodWall"       / "BLOOD_WALL",
    Hemokinesis     => "Hemokinesis"     / "HEMOKINESIS",
    Offering        => "Offering"        / "OFFERING",
    Tremble         => "Tremble"         / "TREMBLE",
    Impervious      => "Impervious"      / "IMPERVIOUS",
    NotYet          => "NotYet"          / "NOT_YET",
    AscendersBane   => "Ascender's Bane" / "ASCENDERS_BANE",
    Slimed          => "Slimed"          / "SLIMED",
    Wound           => "Wound"           / "WOUND",
    Infection       => "Infection"       / "INFECTION",
    Dazed           => "Dazed"           / "DAZED",
    Cinder          => "Cinder"          / "CINDER",
    TrueGrit        => "TrueGrit"        / "TRUE_GRIT",
    BurningPact     => "BurningPact"     / "BURNING_PACT",
    Thrash          => "Thrash"          / "THRASH",
    SecondWind      => "SecondWind"      / "SECOND_WIND",
    Headbutt        => "Headbutt"        / "HEADBUTT",
    FiendFire       => "FiendFire"       / "FIEND_FIRE",
    InfernalBlade   => "InfernalBlade"   / "INFERNAL_BLADE",
    Bludgeon        => "Bludgeon"        / "BLUDGEON",
    TwinStrike      => "TwinStrike"      / "TWIN_STRIKE",
    Break           => "Break"           / "BREAK",
    ShrugItOff      => "ShrugItOff"      / "SHRUG_IT_OFF",
    Taunt           => "Taunt"           / "TAUNT",
    Uppercut        => "Uppercut"        / "UPPERCUT",
    BodySlam        => "BodySlam"        / "BODY_SLAM",
    PerfectedStrike => "PerfectedStrike" / "PERFECTED_STRIKE",
    AshenStrike     => "AshenStrike"     / "ASHEN_STRIKE",
    Bully           => "Bully"           / "BULLY",
    Conflagration   => "Conflagration"   / "CONFLAGRATION",
    TearAsunder     => "TearAsunder"     / "TEAR_ASUNDER",
    Spite           => "Spite"           / "SPITE",
    Dismantle       => "Dismantle"       / "DISMANTLE",
    MoltenFist      => "MoltenFist"      / "MOLTEN_FIST",
    Dominate        => "Dominate"        / "DOMINATE",
    Breakthrough    => "Breakthrough"    / "BREAKTHROUGH",
    SetupStrike     => "Setup Strike"    / "SETUP_STRIKE",
    Unrelenting     => "Unrelenting"     / "UNRELENTING",
    EvilEye         => "Evil Eye"        / "EVIL_EYE",
    ForgottenRitual => "Forgotten Ritual" / "FORGOTTEN_RITUAL",
    Pyre            => "Pyre"            / "PYRE",
    Anger           => "Anger"           / "ANGER",
    DrumOfBattle    => "DrumOfBattle"    / "DRUM_OF_BATTLE",
    Stomp           => "Stomp"           / "STOMP",
    FightMe         => "FightMe"         / "FIGHT_ME",
    StoneArmor      => "StoneArmor"      / "STONE_ARMOR",
    Vicious         => "Vicious"         / "VICIOUS",
    Juggling        => "Juggling"        / "JUGGLING",
    Unmovable       => "Unmovable"       / "UNMOVABLE",
    PactsEnd        => "PactsEnd"        / "PACTS_END",
    HowlFromBeyond  => "HowlFromBeyond"  / "HOWL_FROM_BEYOND",
    Havoc           => "Havoc"           / "HAVOC",
    BattleTrance    => "BattleTrance"    / "BATTLE_TRANCE",
    Whirlwind       => "Whirlwind"       / "WHIRLWIND",
    Cascade         => "Cascade"         / "CASCADE",
});

// ── MonsterId ────────────────────────────────────────────────────────────────

define_ids!(MonsterId {
    JawWorm             => "Jaw Worm"            / "JAW_WORM",
    GremlinNob          => "Gremlin Nob"         / "GREMLIN_NOB",
    Nibbit              => "Nibbit"              / "NIBBIT",
    FuzzyWurmCrawler    => "Fuzzy Wurm Crawler"  / "FUZZY_WURM_CRAWLER",
    TwigSlimeS          => "Twig Slime (S)"      / "TWIG_SLIME_S",
    ShrinkerBeetle      => "Shrinker Beetle"     / "SHRINKER_BEETLE",
    LeafSlimeS          => "Leaf Slime (S)"      / "LEAF_SLIME_S",
    LeafSlimeM          => "Leaf Slime (M)"      / "LEAF_SLIME_M",
    TwigSlimeM          => "Twig Slime (M)"      / "TWIG_SLIME_M",
    Byrdonis            => "Byrdonis"            / "BYRDONIS",
    Inklet              => "Inklet"              / "INKLET",
    Vantom              => "Vantom"              / "VANTOM",
    SnappingJaxfruit    => "Snapping Jaxfruit"   / "SNAPPING_JAXFRUIT",
    AxeRubyRaider       => "Axe Ruby Raider"     / "AXE_RUBY_RAIDER",
    AssassinRubyRaider  => "Assassin Ruby Raider" / "ASSASSIN_RUBY_RAIDER",
    BruteRubyRaider     => "Brute Ruby Raider"   / "BRUTE_RUBY_RAIDER",
    CrossbowRubyRaider  => "Crossbow Ruby Raider" / "CROSSBOW_RUBY_RAIDER",
    SlitheringStrangler => "Slithering Strangler" / "SLITHERING_STRANGLER",
    CubexConstruct      => "Cubex Construct"     / "CUBEX_CONSTRUCT",
    KinPriest           => "Kin Priest"          / "KIN_PRIEST",
    KinFollower         => "Kin Follower"        / "KIN_FOLLOWER",
    PhrogParasite       => "Phrog Parasite"      / "PHROG_PARASITE",
    Wriggler            => "Wriggler"            / "WRIGGLER",
    TrackerRubyRaider   => "Tracker Ruby Raider" / "TRACKER_RUBY_RAIDER",
    Mawler              => "Mawler"              / "MAWLER",
    VineShambler        => "Vine Shambler"       / "VINE_SHAMBLER",
    BygoneEffigy        => "Bygone Effigy"       / "BYGONE_EFFIGY",
    Flyconid            => "Flyconid"            / "FLYCONID",
    Fogmog              => "Fogmog"              / "FOGMOG",
    CeremonialBeast     => "Ceremonial Beast"    / "CEREMONIAL_BEAST",
    EyeWithTeeth        => "Eye With Teeth"      / "EYE_WITH_TEETH",
});
// END GENERATED

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn card_id_round_trips() {
        assert_eq!(CardId::all().len(), 79);
        for &v in CardId::all() {
            assert_eq!(CardId::from_str(v.as_str()), Some(v), "from_str round-trip failed for {:?}", v);
            assert_eq!(CardId::from_sts2(v.sts2_id()), Some(v), "from_sts2 round-trip failed for {:?}", v);
        }
    }

    #[test]
    fn monster_id_round_trips() {
        assert_eq!(MonsterId::all().len(), 31);
        for &v in MonsterId::all() {
            assert_eq!(MonsterId::from_str(v.as_str()), Some(v), "from_str round-trip failed for {:?}", v);
            assert_eq!(MonsterId::from_sts2(v.sts2_id()), Some(v), "from_sts2 round-trip failed for {:?}", v);
        }
    }
}
