//! Typed identifiers for cards and monsters.
//! Initially generated by scripts/gen_ids.py (HOL-82). After HOL-83, cards.rs
//! uses CardId directly, so new variants must be added here and in cards.rs manually.

// ── CardId ───────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CardId {
    StrikeIronclad, // "Strike"
    DefendIronclad, // "Defend"
    Bash, // "Bash"
    IronWave, // "Iron Wave"
    Inflame, // "Inflame"
    SwordBoomerang, // "Sword Boomerang"
    Thunderclap, // "Thunderclap"
    Rage, // "Rage"
    DemonForm, // "DemonForm"
    CrimsonMantle, // "CrimsonMantle"
    Inferno, // "Inferno"
    Aggression, // "Aggression"
    DarkEmbrace, // "DarkEmbrace"
    FeelNoPain, // "FeelNoPain"
    Barricade, // "Barricade"
    Juggernaut, // "Juggernaut"
    FlameBarrier, // "FlameBarrier"
    Colossus, // "Colossus"
    Corruption, // "Corruption"
    Cruelty, // "Cruelty"
    Mangle, // "Mangle"
    OneTwoPunch, // "OneTwoPunch"
    PommelStrike, // "Pommel Strike"
    Bloodletting, // "Bloodletting"
    BloodWall, // "BloodWall"
    Hemokinesis, // "Hemokinesis"
    Offering, // "Offering"
    Tremble, // "Tremble"
    Impervious, // "Impervious"
    NotYet, // "NotYet"
    AscendersBane, // "Ascender's Bane"
    Slimed, // "Slimed"
    Wound, // "Wound"
    Infection, // "Infection"
    Dazed, // "Dazed"
    Cinder, // "Cinder"
    TrueGrit, // "TrueGrit"
    BurningPact, // "BurningPact"
    Thrash, // "Thrash"
    SecondWind, // "SecondWind"
    Headbutt, // "Headbutt"
    FiendFire, // "FiendFire"
    InfernalBlade, // "InfernalBlade"
    Bludgeon, // "Bludgeon"
    TwinStrike, // "TwinStrike"
    Break, // "Break"
    ShrugItOff, // "ShrugItOff"
    Taunt, // "Taunt"
    Uppercut, // "Uppercut"
    BodySlam, // "BodySlam"
    PerfectedStrike, // "PerfectedStrike"
    AshenStrike, // "AshenStrike"
    Bully, // "Bully"
    Conflagration, // "Conflagration"
    TearAsunder, // "TearAsunder"
    Spite, // "Spite"
    Dismantle, // "Dismantle"
    MoltenFist, // "MoltenFist"
    Dominate, // "Dominate"
    Breakthrough, // "Breakthrough"
    SetupStrike, // "Setup Strike"
    Unrelenting, // "Unrelenting"
    EvilEye, // "Evil Eye"
    ForgottenRitual, // "Forgotten Ritual"
    Pyre, // "Pyre"
    Anger, // "Anger"
    DrumOfBattle, // "DrumOfBattle"
    Stomp, // "Stomp"
    FightMe, // "FightMe"
    StoneArmor, // "StoneArmor"
    Vicious, // "Vicious"
    Juggling, // "Juggling"
    Unmovable, // "Unmovable"
    PactsEnd, // "PactsEnd"
    HowlFromBeyond, // "HowlFromBeyond"
    Havoc, // "Havoc"
    BattleTrance, // "BattleTrance"
    Whirlwind, // "Whirlwind"
    Cascade, // "Cascade"
}

impl CardId {
    /// Canonical sim display name.
    pub fn as_str(self) -> &'static str {
        match self {
            CardId::StrikeIronclad => "Strike",
            CardId::DefendIronclad => "Defend",
            CardId::Bash => "Bash",
            CardId::IronWave => "Iron Wave",
            CardId::Inflame => "Inflame",
            CardId::SwordBoomerang => "Sword Boomerang",
            CardId::Thunderclap => "Thunderclap",
            CardId::Rage => "Rage",
            CardId::DemonForm => "DemonForm",
            CardId::CrimsonMantle => "CrimsonMantle",
            CardId::Inferno => "Inferno",
            CardId::Aggression => "Aggression",
            CardId::DarkEmbrace => "DarkEmbrace",
            CardId::FeelNoPain => "FeelNoPain",
            CardId::Barricade => "Barricade",
            CardId::Juggernaut => "Juggernaut",
            CardId::FlameBarrier => "FlameBarrier",
            CardId::Colossus => "Colossus",
            CardId::Corruption => "Corruption",
            CardId::Cruelty => "Cruelty",
            CardId::Mangle => "Mangle",
            CardId::OneTwoPunch => "OneTwoPunch",
            CardId::PommelStrike => "Pommel Strike",
            CardId::Bloodletting => "Bloodletting",
            CardId::BloodWall => "BloodWall",
            CardId::Hemokinesis => "Hemokinesis",
            CardId::Offering => "Offering",
            CardId::Tremble => "Tremble",
            CardId::Impervious => "Impervious",
            CardId::NotYet => "NotYet",
            CardId::AscendersBane => "Ascender's Bane",
            CardId::Slimed => "Slimed",
            CardId::Wound => "Wound",
            CardId::Infection => "Infection",
            CardId::Dazed => "Dazed",
            CardId::Cinder => "Cinder",
            CardId::TrueGrit => "TrueGrit",
            CardId::BurningPact => "BurningPact",
            CardId::Thrash => "Thrash",
            CardId::SecondWind => "SecondWind",
            CardId::Headbutt => "Headbutt",
            CardId::FiendFire => "FiendFire",
            CardId::InfernalBlade => "InfernalBlade",
            CardId::Bludgeon => "Bludgeon",
            CardId::TwinStrike => "TwinStrike",
            CardId::Break => "Break",
            CardId::ShrugItOff => "ShrugItOff",
            CardId::Taunt => "Taunt",
            CardId::Uppercut => "Uppercut",
            CardId::BodySlam => "BodySlam",
            CardId::PerfectedStrike => "PerfectedStrike",
            CardId::AshenStrike => "AshenStrike",
            CardId::Bully => "Bully",
            CardId::Conflagration => "Conflagration",
            CardId::TearAsunder => "TearAsunder",
            CardId::Spite => "Spite",
            CardId::Dismantle => "Dismantle",
            CardId::MoltenFist => "MoltenFist",
            CardId::Dominate => "Dominate",
            CardId::Breakthrough => "Breakthrough",
            CardId::SetupStrike => "Setup Strike",
            CardId::Unrelenting => "Unrelenting",
            CardId::EvilEye => "Evil Eye",
            CardId::ForgottenRitual => "Forgotten Ritual",
            CardId::Pyre => "Pyre",
            CardId::Anger => "Anger",
            CardId::DrumOfBattle => "DrumOfBattle",
            CardId::Stomp => "Stomp",
            CardId::FightMe => "FightMe",
            CardId::StoneArmor => "StoneArmor",
            CardId::Vicious => "Vicious",
            CardId::Juggling => "Juggling",
            CardId::Unmovable => "Unmovable",
            CardId::PactsEnd => "PactsEnd",
            CardId::HowlFromBeyond => "HowlFromBeyond",
            CardId::Havoc => "Havoc",
            CardId::BattleTrance => "BattleTrance",
            CardId::Whirlwind => "Whirlwind",
            CardId::Cascade => "Cascade",
        }
    }

    /// Parse from sim display name. Returns `None` for unknown names.
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "Strike" => Some(CardId::StrikeIronclad),
            "Defend" => Some(CardId::DefendIronclad),
            "Bash" => Some(CardId::Bash),
            "Iron Wave" => Some(CardId::IronWave),
            "Inflame" => Some(CardId::Inflame),
            "Sword Boomerang" => Some(CardId::SwordBoomerang),
            "Thunderclap" => Some(CardId::Thunderclap),
            "Rage" => Some(CardId::Rage),
            "DemonForm" => Some(CardId::DemonForm),
            "CrimsonMantle" => Some(CardId::CrimsonMantle),
            "Inferno" => Some(CardId::Inferno),
            "Aggression" => Some(CardId::Aggression),
            "DarkEmbrace" => Some(CardId::DarkEmbrace),
            "FeelNoPain" => Some(CardId::FeelNoPain),
            "Barricade" => Some(CardId::Barricade),
            "Juggernaut" => Some(CardId::Juggernaut),
            "FlameBarrier" => Some(CardId::FlameBarrier),
            "Colossus" => Some(CardId::Colossus),
            "Corruption" => Some(CardId::Corruption),
            "Cruelty" => Some(CardId::Cruelty),
            "Mangle" => Some(CardId::Mangle),
            "OneTwoPunch" => Some(CardId::OneTwoPunch),
            "Pommel Strike" => Some(CardId::PommelStrike),
            "Bloodletting" => Some(CardId::Bloodletting),
            "BloodWall" => Some(CardId::BloodWall),
            "Hemokinesis" => Some(CardId::Hemokinesis),
            "Offering" => Some(CardId::Offering),
            "Tremble" => Some(CardId::Tremble),
            "Impervious" => Some(CardId::Impervious),
            "NotYet" => Some(CardId::NotYet),
            "Ascender's Bane" => Some(CardId::AscendersBane),
            "Slimed" => Some(CardId::Slimed),
            "Wound" => Some(CardId::Wound),
            "Infection" => Some(CardId::Infection),
            "Dazed" => Some(CardId::Dazed),
            "Cinder" => Some(CardId::Cinder),
            "TrueGrit" => Some(CardId::TrueGrit),
            "BurningPact" => Some(CardId::BurningPact),
            "Thrash" => Some(CardId::Thrash),
            "SecondWind" => Some(CardId::SecondWind),
            "Headbutt" => Some(CardId::Headbutt),
            "FiendFire" => Some(CardId::FiendFire),
            "InfernalBlade" => Some(CardId::InfernalBlade),
            "Bludgeon" => Some(CardId::Bludgeon),
            "TwinStrike" => Some(CardId::TwinStrike),
            "Break" => Some(CardId::Break),
            "ShrugItOff" => Some(CardId::ShrugItOff),
            "Taunt" => Some(CardId::Taunt),
            "Uppercut" => Some(CardId::Uppercut),
            "BodySlam" => Some(CardId::BodySlam),
            "PerfectedStrike" => Some(CardId::PerfectedStrike),
            "AshenStrike" => Some(CardId::AshenStrike),
            "Bully" => Some(CardId::Bully),
            "Conflagration" => Some(CardId::Conflagration),
            "TearAsunder" => Some(CardId::TearAsunder),
            "Spite" => Some(CardId::Spite),
            "Dismantle" => Some(CardId::Dismantle),
            "MoltenFist" => Some(CardId::MoltenFist),
            "Dominate" => Some(CardId::Dominate),
            "Breakthrough" => Some(CardId::Breakthrough),
            "Setup Strike" => Some(CardId::SetupStrike),
            "Unrelenting" => Some(CardId::Unrelenting),
            "Evil Eye" => Some(CardId::EvilEye),
            "Forgotten Ritual" => Some(CardId::ForgottenRitual),
            "Pyre" => Some(CardId::Pyre),
            "Anger" => Some(CardId::Anger),
            "DrumOfBattle" => Some(CardId::DrumOfBattle),
            "Stomp" => Some(CardId::Stomp),
            "FightMe" => Some(CardId::FightMe),
            "StoneArmor" => Some(CardId::StoneArmor),
            "Vicious" => Some(CardId::Vicious),
            "Juggling" => Some(CardId::Juggling),
            "Unmovable" => Some(CardId::Unmovable),
            "PactsEnd" => Some(CardId::PactsEnd),
            "HowlFromBeyond" => Some(CardId::HowlFromBeyond),
            "Havoc" => Some(CardId::Havoc),
            "BattleTrance" => Some(CardId::BattleTrance),
            "Whirlwind" => Some(CardId::Whirlwind),
            "Cascade" => Some(CardId::Cascade),
            _ => None,
        }
    }

    /// STS2 model ID (e.g. `STRIKE_IRONCLAD`).
    pub fn sts2_id(self) -> &'static str {
        match self {
            CardId::StrikeIronclad => "STRIKE_IRONCLAD",
            CardId::DefendIronclad => "DEFEND_IRONCLAD",
            CardId::Bash => "BASH",
            CardId::IronWave => "IRON_WAVE",
            CardId::Inflame => "INFLAME",
            CardId::SwordBoomerang => "SWORD_BOOMERANG",
            CardId::Thunderclap => "THUNDERCLAP",
            CardId::Rage => "RAGE",
            CardId::DemonForm => "DEMON_FORM",
            CardId::CrimsonMantle => "CRIMSON_MANTLE",
            CardId::Inferno => "INFERNO",
            CardId::Aggression => "AGGRESSION",
            CardId::DarkEmbrace => "DARK_EMBRACE",
            CardId::FeelNoPain => "FEEL_NO_PAIN",
            CardId::Barricade => "BARRICADE",
            CardId::Juggernaut => "JUGGERNAUT",
            CardId::FlameBarrier => "FLAME_BARRIER",
            CardId::Colossus => "COLOSSUS",
            CardId::Corruption => "CORRUPTION",
            CardId::Cruelty => "CRUELTY",
            CardId::Mangle => "MANGLE",
            CardId::OneTwoPunch => "ONE_TWO_PUNCH",
            CardId::PommelStrike => "POMMEL_STRIKE",
            CardId::Bloodletting => "BLOODLETTING",
            CardId::BloodWall => "BLOOD_WALL",
            CardId::Hemokinesis => "HEMOKINESIS",
            CardId::Offering => "OFFERING",
            CardId::Tremble => "TREMBLE",
            CardId::Impervious => "IMPERVIOUS",
            CardId::NotYet => "NOT_YET",
            CardId::AscendersBane => "ASCENDERS_BANE",
            CardId::Slimed => "SLIMED",
            CardId::Wound => "WOUND",
            CardId::Infection => "INFECTION",
            CardId::Dazed => "DAZED",
            CardId::Cinder => "CINDER",
            CardId::TrueGrit => "TRUE_GRIT",
            CardId::BurningPact => "BURNING_PACT",
            CardId::Thrash => "THRASH",
            CardId::SecondWind => "SECOND_WIND",
            CardId::Headbutt => "HEADBUTT",
            CardId::FiendFire => "FIEND_FIRE",
            CardId::InfernalBlade => "INFERNAL_BLADE",
            CardId::Bludgeon => "BLUDGEON",
            CardId::TwinStrike => "TWIN_STRIKE",
            CardId::Break => "BREAK",
            CardId::ShrugItOff => "SHRUG_IT_OFF",
            CardId::Taunt => "TAUNT",
            CardId::Uppercut => "UPPERCUT",
            CardId::BodySlam => "BODY_SLAM",
            CardId::PerfectedStrike => "PERFECTED_STRIKE",
            CardId::AshenStrike => "ASHEN_STRIKE",
            CardId::Bully => "BULLY",
            CardId::Conflagration => "CONFLAGRATION",
            CardId::TearAsunder => "TEAR_ASUNDER",
            CardId::Spite => "SPITE",
            CardId::Dismantle => "DISMANTLE",
            CardId::MoltenFist => "MOLTEN_FIST",
            CardId::Dominate => "DOMINATE",
            CardId::Breakthrough => "BREAKTHROUGH",
            CardId::SetupStrike => "SETUP_STRIKE",
            CardId::Unrelenting => "UNRELENTING",
            CardId::EvilEye => "EVIL_EYE",
            CardId::ForgottenRitual => "FORGOTTEN_RITUAL",
            CardId::Pyre => "PYRE",
            CardId::Anger => "ANGER",
            CardId::DrumOfBattle => "DRUM_OF_BATTLE",
            CardId::Stomp => "STOMP",
            CardId::FightMe => "FIGHT_ME",
            CardId::StoneArmor => "STONE_ARMOR",
            CardId::Vicious => "VICIOUS",
            CardId::Juggling => "JUGGLING",
            CardId::Unmovable => "UNMOVABLE",
            CardId::PactsEnd => "PACTS_END",
            CardId::HowlFromBeyond => "HOWL_FROM_BEYOND",
            CardId::Havoc => "HAVOC",
            CardId::BattleTrance => "BATTLE_TRANCE",
            CardId::Whirlwind => "WHIRLWIND",
            CardId::Cascade => "CASCADE",
        }
    }

    /// Parse from STS2 model ID. Returns `None` for unknown IDs.
    pub fn from_sts2(s: &str) -> Option<Self> {
        match s {
            "STRIKE_IRONCLAD" => Some(CardId::StrikeIronclad),
            "DEFEND_IRONCLAD" => Some(CardId::DefendIronclad),
            "BASH" => Some(CardId::Bash),
            "IRON_WAVE" => Some(CardId::IronWave),
            "INFLAME" => Some(CardId::Inflame),
            "SWORD_BOOMERANG" => Some(CardId::SwordBoomerang),
            "THUNDERCLAP" => Some(CardId::Thunderclap),
            "RAGE" => Some(CardId::Rage),
            "DEMON_FORM" => Some(CardId::DemonForm),
            "CRIMSON_MANTLE" => Some(CardId::CrimsonMantle),
            "INFERNO" => Some(CardId::Inferno),
            "AGGRESSION" => Some(CardId::Aggression),
            "DARK_EMBRACE" => Some(CardId::DarkEmbrace),
            "FEEL_NO_PAIN" => Some(CardId::FeelNoPain),
            "BARRICADE" => Some(CardId::Barricade),
            "JUGGERNAUT" => Some(CardId::Juggernaut),
            "FLAME_BARRIER" => Some(CardId::FlameBarrier),
            "COLOSSUS" => Some(CardId::Colossus),
            "CORRUPTION" => Some(CardId::Corruption),
            "CRUELTY" => Some(CardId::Cruelty),
            "MANGLE" => Some(CardId::Mangle),
            "ONE_TWO_PUNCH" => Some(CardId::OneTwoPunch),
            "POMMEL_STRIKE" => Some(CardId::PommelStrike),
            "BLOODLETTING" => Some(CardId::Bloodletting),
            "BLOOD_WALL" => Some(CardId::BloodWall),
            "HEMOKINESIS" => Some(CardId::Hemokinesis),
            "OFFERING" => Some(CardId::Offering),
            "TREMBLE" => Some(CardId::Tremble),
            "IMPERVIOUS" => Some(CardId::Impervious),
            "NOT_YET" => Some(CardId::NotYet),
            "ASCENDERS_BANE" => Some(CardId::AscendersBane),
            "SLIMED" => Some(CardId::Slimed),
            "WOUND" => Some(CardId::Wound),
            "INFECTION" => Some(CardId::Infection),
            "DAZED" => Some(CardId::Dazed),
            "CINDER" => Some(CardId::Cinder),
            "TRUE_GRIT" => Some(CardId::TrueGrit),
            "BURNING_PACT" => Some(CardId::BurningPact),
            "THRASH" => Some(CardId::Thrash),
            "SECOND_WIND" => Some(CardId::SecondWind),
            "HEADBUTT" => Some(CardId::Headbutt),
            "FIEND_FIRE" => Some(CardId::FiendFire),
            "INFERNAL_BLADE" => Some(CardId::InfernalBlade),
            "BLUDGEON" => Some(CardId::Bludgeon),
            "TWIN_STRIKE" => Some(CardId::TwinStrike),
            "BREAK" => Some(CardId::Break),
            "SHRUG_IT_OFF" => Some(CardId::ShrugItOff),
            "TAUNT" => Some(CardId::Taunt),
            "UPPERCUT" => Some(CardId::Uppercut),
            "BODY_SLAM" => Some(CardId::BodySlam),
            "PERFECTED_STRIKE" => Some(CardId::PerfectedStrike),
            "ASHEN_STRIKE" => Some(CardId::AshenStrike),
            "BULLY" => Some(CardId::Bully),
            "CONFLAGRATION" => Some(CardId::Conflagration),
            "TEAR_ASUNDER" => Some(CardId::TearAsunder),
            "SPITE" => Some(CardId::Spite),
            "DISMANTLE" => Some(CardId::Dismantle),
            "MOLTEN_FIST" => Some(CardId::MoltenFist),
            "DOMINATE" => Some(CardId::Dominate),
            "BREAKTHROUGH" => Some(CardId::Breakthrough),
            "SETUP_STRIKE" => Some(CardId::SetupStrike),
            "UNRELENTING" => Some(CardId::Unrelenting),
            "EVIL_EYE" => Some(CardId::EvilEye),
            "FORGOTTEN_RITUAL" => Some(CardId::ForgottenRitual),
            "PYRE" => Some(CardId::Pyre),
            "ANGER" => Some(CardId::Anger),
            "DRUM_OF_BATTLE" => Some(CardId::DrumOfBattle),
            "STOMP" => Some(CardId::Stomp),
            "FIGHT_ME" => Some(CardId::FightMe),
            "STONE_ARMOR" => Some(CardId::StoneArmor),
            "VICIOUS" => Some(CardId::Vicious),
            "JUGGLING" => Some(CardId::Juggling),
            "UNMOVABLE" => Some(CardId::Unmovable),
            "PACTS_END" => Some(CardId::PactsEnd),
            "HOWL_FROM_BEYOND" => Some(CardId::HowlFromBeyond),
            "HAVOC" => Some(CardId::Havoc),
            "BATTLE_TRANCE" => Some(CardId::BattleTrance),
            "WHIRLWIND" => Some(CardId::Whirlwind),
            "CASCADE" => Some(CardId::Cascade),
            _ => None,
        }
    }

    /// Every `CardId` variant.
    pub fn all() -> &'static [CardId] {
        &[
            CardId::StrikeIronclad,
            CardId::DefendIronclad,
            CardId::Bash,
            CardId::IronWave,
            CardId::Inflame,
            CardId::SwordBoomerang,
            CardId::Thunderclap,
            CardId::Rage,
            CardId::DemonForm,
            CardId::CrimsonMantle,
            CardId::Inferno,
            CardId::Aggression,
            CardId::DarkEmbrace,
            CardId::FeelNoPain,
            CardId::Barricade,
            CardId::Juggernaut,
            CardId::FlameBarrier,
            CardId::Colossus,
            CardId::Corruption,
            CardId::Cruelty,
            CardId::Mangle,
            CardId::OneTwoPunch,
            CardId::PommelStrike,
            CardId::Bloodletting,
            CardId::BloodWall,
            CardId::Hemokinesis,
            CardId::Offering,
            CardId::Tremble,
            CardId::Impervious,
            CardId::NotYet,
            CardId::AscendersBane,
            CardId::Slimed,
            CardId::Wound,
            CardId::Infection,
            CardId::Dazed,
            CardId::Cinder,
            CardId::TrueGrit,
            CardId::BurningPact,
            CardId::Thrash,
            CardId::SecondWind,
            CardId::Headbutt,
            CardId::FiendFire,
            CardId::InfernalBlade,
            CardId::Bludgeon,
            CardId::TwinStrike,
            CardId::Break,
            CardId::ShrugItOff,
            CardId::Taunt,
            CardId::Uppercut,
            CardId::BodySlam,
            CardId::PerfectedStrike,
            CardId::AshenStrike,
            CardId::Bully,
            CardId::Conflagration,
            CardId::TearAsunder,
            CardId::Spite,
            CardId::Dismantle,
            CardId::MoltenFist,
            CardId::Dominate,
            CardId::Breakthrough,
            CardId::SetupStrike,
            CardId::Unrelenting,
            CardId::EvilEye,
            CardId::ForgottenRitual,
            CardId::Pyre,
            CardId::Anger,
            CardId::DrumOfBattle,
            CardId::Stomp,
            CardId::FightMe,
            CardId::StoneArmor,
            CardId::Vicious,
            CardId::Juggling,
            CardId::Unmovable,
            CardId::PactsEnd,
            CardId::HowlFromBeyond,
            CardId::Havoc,
            CardId::BattleTrance,
            CardId::Whirlwind,
            CardId::Cascade,
        ]
    }
}

// ── MonsterId ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MonsterId {
    JawWorm, // "Jaw Worm"
    GremlinNob, // "Gremlin Nob"
    Nibbit, // "Nibbit"
    FuzzyWurmCrawler, // "Fuzzy Wurm Crawler"
    TwigSlimeS, // "Twig Slime (S)"
    ShrinkerBeetle, // "Shrinker Beetle"
    LeafSlimeS, // "Leaf Slime (S)"
    LeafSlimeM, // "Leaf Slime (M)"
    TwigSlimeM, // "Twig Slime (M)"
    Byrdonis, // "Byrdonis"
    Inklet, // "Inklet"
    Vantom, // "Vantom"
    SnappingJaxfruit, // "Snapping Jaxfruit"
    AxeRubyRaider, // "Axe Ruby Raider"
    AssassinRubyRaider, // "Assassin Ruby Raider"
    BruteRubyRaider, // "Brute Ruby Raider"
    CrossbowRubyRaider, // "Crossbow Ruby Raider"
    SlitheringStrangler, // "Slithering Strangler"
    CubexConstruct, // "Cubex Construct"
    KinPriest, // "Kin Priest"
    KinFollower, // "Kin Follower"
    PhrogParasite, // "Phrog Parasite"
    Wriggler, // "Wriggler"
    TrackerRubyRaider, // "Tracker Ruby Raider"
    Mawler, // "Mawler"
    VineShambler, // "Vine Shambler"
    BygoneEffigy, // "Bygone Effigy"
    Flyconid, // "Flyconid"
    Fogmog, // "Fogmog"
    CeremonialBeast, // "Ceremonial Beast"
    EyeWithTeeth, // "Eye With Teeth"
}

impl MonsterId {
    /// Canonical sim display name.
    pub fn as_str(self) -> &'static str {
        match self {
            MonsterId::JawWorm => "Jaw Worm",
            MonsterId::GremlinNob => "Gremlin Nob",
            MonsterId::Nibbit => "Nibbit",
            MonsterId::FuzzyWurmCrawler => "Fuzzy Wurm Crawler",
            MonsterId::TwigSlimeS => "Twig Slime (S)",
            MonsterId::ShrinkerBeetle => "Shrinker Beetle",
            MonsterId::LeafSlimeS => "Leaf Slime (S)",
            MonsterId::LeafSlimeM => "Leaf Slime (M)",
            MonsterId::TwigSlimeM => "Twig Slime (M)",
            MonsterId::Byrdonis => "Byrdonis",
            MonsterId::Inklet => "Inklet",
            MonsterId::Vantom => "Vantom",
            MonsterId::SnappingJaxfruit => "Snapping Jaxfruit",
            MonsterId::AxeRubyRaider => "Axe Ruby Raider",
            MonsterId::AssassinRubyRaider => "Assassin Ruby Raider",
            MonsterId::BruteRubyRaider => "Brute Ruby Raider",
            MonsterId::CrossbowRubyRaider => "Crossbow Ruby Raider",
            MonsterId::SlitheringStrangler => "Slithering Strangler",
            MonsterId::CubexConstruct => "Cubex Construct",
            MonsterId::KinPriest => "Kin Priest",
            MonsterId::KinFollower => "Kin Follower",
            MonsterId::PhrogParasite => "Phrog Parasite",
            MonsterId::Wriggler => "Wriggler",
            MonsterId::TrackerRubyRaider => "Tracker Ruby Raider",
            MonsterId::Mawler => "Mawler",
            MonsterId::VineShambler => "Vine Shambler",
            MonsterId::BygoneEffigy => "Bygone Effigy",
            MonsterId::Flyconid => "Flyconid",
            MonsterId::Fogmog => "Fogmog",
            MonsterId::CeremonialBeast => "Ceremonial Beast",
            MonsterId::EyeWithTeeth => "Eye With Teeth",
        }
    }

    /// Parse from sim display name.
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "Jaw Worm" => Some(MonsterId::JawWorm),
            "Gremlin Nob" => Some(MonsterId::GremlinNob),
            "Nibbit" => Some(MonsterId::Nibbit),
            "Fuzzy Wurm Crawler" => Some(MonsterId::FuzzyWurmCrawler),
            "Twig Slime (S)" => Some(MonsterId::TwigSlimeS),
            "Shrinker Beetle" => Some(MonsterId::ShrinkerBeetle),
            "Leaf Slime (S)" => Some(MonsterId::LeafSlimeS),
            "Leaf Slime (M)" => Some(MonsterId::LeafSlimeM),
            "Twig Slime (M)" => Some(MonsterId::TwigSlimeM),
            "Byrdonis" => Some(MonsterId::Byrdonis),
            "Inklet" => Some(MonsterId::Inklet),
            "Vantom" => Some(MonsterId::Vantom),
            "Snapping Jaxfruit" => Some(MonsterId::SnappingJaxfruit),
            "Axe Ruby Raider" => Some(MonsterId::AxeRubyRaider),
            "Assassin Ruby Raider" => Some(MonsterId::AssassinRubyRaider),
            "Brute Ruby Raider" => Some(MonsterId::BruteRubyRaider),
            "Crossbow Ruby Raider" => Some(MonsterId::CrossbowRubyRaider),
            "Slithering Strangler" => Some(MonsterId::SlitheringStrangler),
            "Cubex Construct" => Some(MonsterId::CubexConstruct),
            "Kin Priest" => Some(MonsterId::KinPriest),
            "Kin Follower" => Some(MonsterId::KinFollower),
            "Phrog Parasite" => Some(MonsterId::PhrogParasite),
            "Wriggler" => Some(MonsterId::Wriggler),
            "Tracker Ruby Raider" => Some(MonsterId::TrackerRubyRaider),
            "Mawler" => Some(MonsterId::Mawler),
            "Vine Shambler" => Some(MonsterId::VineShambler),
            "Bygone Effigy" => Some(MonsterId::BygoneEffigy),
            "Flyconid" => Some(MonsterId::Flyconid),
            "Fogmog" => Some(MonsterId::Fogmog),
            "Ceremonial Beast" => Some(MonsterId::CeremonialBeast),
            "Eye With Teeth" => Some(MonsterId::EyeWithTeeth),
            _ => None,
        }
    }

    /// STS2 model ID (e.g. `JAW_WORM`).
    pub fn sts2_id(self) -> &'static str {
        match self {
            MonsterId::JawWorm => "JAW_WORM",
            MonsterId::GremlinNob => "GREMLIN_NOB",
            MonsterId::Nibbit => "NIBBIT",
            MonsterId::FuzzyWurmCrawler => "FUZZY_WURM_CRAWLER",
            MonsterId::TwigSlimeS => "TWIG_SLIME_S",
            MonsterId::ShrinkerBeetle => "SHRINKER_BEETLE",
            MonsterId::LeafSlimeS => "LEAF_SLIME_S",
            MonsterId::LeafSlimeM => "LEAF_SLIME_M",
            MonsterId::TwigSlimeM => "TWIG_SLIME_M",
            MonsterId::Byrdonis => "BYRDONIS",
            MonsterId::Inklet => "INKLET",
            MonsterId::Vantom => "VANTOM",
            MonsterId::SnappingJaxfruit => "SNAPPING_JAXFRUIT",
            MonsterId::AxeRubyRaider => "AXE_RUBY_RAIDER",
            MonsterId::AssassinRubyRaider => "ASSASSIN_RUBY_RAIDER",
            MonsterId::BruteRubyRaider => "BRUTE_RUBY_RAIDER",
            MonsterId::CrossbowRubyRaider => "CROSSBOW_RUBY_RAIDER",
            MonsterId::SlitheringStrangler => "SLITHERING_STRANGLER",
            MonsterId::CubexConstruct => "CUBEX_CONSTRUCT",
            MonsterId::KinPriest => "KIN_PRIEST",
            MonsterId::KinFollower => "KIN_FOLLOWER",
            MonsterId::PhrogParasite => "PHROG_PARASITE",
            MonsterId::Wriggler => "WRIGGLER",
            MonsterId::TrackerRubyRaider => "TRACKER_RUBY_RAIDER",
            MonsterId::Mawler => "MAWLER",
            MonsterId::VineShambler => "VINE_SHAMBLER",
            MonsterId::BygoneEffigy => "BYGONE_EFFIGY",
            MonsterId::Flyconid => "FLYCONID",
            MonsterId::Fogmog => "FOGMOG",
            MonsterId::CeremonialBeast => "CEREMONIAL_BEAST",
            MonsterId::EyeWithTeeth => "EYE_WITH_TEETH",
        }
    }

    /// Parse from STS2 model ID.
    pub fn from_sts2(s: &str) -> Option<Self> {
        match s {
            "JAW_WORM" => Some(MonsterId::JawWorm),
            "GREMLIN_NOB" => Some(MonsterId::GremlinNob),
            "NIBBIT" => Some(MonsterId::Nibbit),
            "FUZZY_WURM_CRAWLER" => Some(MonsterId::FuzzyWurmCrawler),
            "TWIG_SLIME_S" => Some(MonsterId::TwigSlimeS),
            "SHRINKER_BEETLE" => Some(MonsterId::ShrinkerBeetle),
            "LEAF_SLIME_S" => Some(MonsterId::LeafSlimeS),
            "LEAF_SLIME_M" => Some(MonsterId::LeafSlimeM),
            "TWIG_SLIME_M" => Some(MonsterId::TwigSlimeM),
            "BYRDONIS" => Some(MonsterId::Byrdonis),
            "INKLET" => Some(MonsterId::Inklet),
            "VANTOM" => Some(MonsterId::Vantom),
            "SNAPPING_JAXFRUIT" => Some(MonsterId::SnappingJaxfruit),
            "AXE_RUBY_RAIDER" => Some(MonsterId::AxeRubyRaider),
            "ASSASSIN_RUBY_RAIDER" => Some(MonsterId::AssassinRubyRaider),
            "BRUTE_RUBY_RAIDER" => Some(MonsterId::BruteRubyRaider),
            "CROSSBOW_RUBY_RAIDER" => Some(MonsterId::CrossbowRubyRaider),
            "SLITHERING_STRANGLER" => Some(MonsterId::SlitheringStrangler),
            "CUBEX_CONSTRUCT" => Some(MonsterId::CubexConstruct),
            "KIN_PRIEST" => Some(MonsterId::KinPriest),
            "KIN_FOLLOWER" => Some(MonsterId::KinFollower),
            "PHROG_PARASITE" => Some(MonsterId::PhrogParasite),
            "WRIGGLER" => Some(MonsterId::Wriggler),
            "TRACKER_RUBY_RAIDER" => Some(MonsterId::TrackerRubyRaider),
            "MAWLER" => Some(MonsterId::Mawler),
            "VINE_SHAMBLER" => Some(MonsterId::VineShambler),
            "BYGONE_EFFIGY" => Some(MonsterId::BygoneEffigy),
            "FLYCONID" => Some(MonsterId::Flyconid),
            "FOGMOG" => Some(MonsterId::Fogmog),
            "CEREMONIAL_BEAST" => Some(MonsterId::CeremonialBeast),
            "EYE_WITH_TEETH" => Some(MonsterId::EyeWithTeeth),
            _ => None,
        }
    }

    /// Every `MonsterId` variant.
    pub fn all() -> &'static [MonsterId] {
        &[
            MonsterId::JawWorm,
            MonsterId::GremlinNob,
            MonsterId::Nibbit,
            MonsterId::FuzzyWurmCrawler,
            MonsterId::TwigSlimeS,
            MonsterId::ShrinkerBeetle,
            MonsterId::LeafSlimeS,
            MonsterId::LeafSlimeM,
            MonsterId::TwigSlimeM,
            MonsterId::Byrdonis,
            MonsterId::Inklet,
            MonsterId::Vantom,
            MonsterId::SnappingJaxfruit,
            MonsterId::AxeRubyRaider,
            MonsterId::AssassinRubyRaider,
            MonsterId::BruteRubyRaider,
            MonsterId::CrossbowRubyRaider,
            MonsterId::SlitheringStrangler,
            MonsterId::CubexConstruct,
            MonsterId::KinPriest,
            MonsterId::KinFollower,
            MonsterId::PhrogParasite,
            MonsterId::Wriggler,
            MonsterId::TrackerRubyRaider,
            MonsterId::Mawler,
            MonsterId::VineShambler,
            MonsterId::BygoneEffigy,
            MonsterId::Flyconid,
            MonsterId::Fogmog,
            MonsterId::CeremonialBeast,
            MonsterId::EyeWithTeeth,
        ]
    }
}
